# Welcome to Jekyll!

# Site settings
# These are used to personalize your new site.
title: Arctic Llamas Announcements
email: aidric.tolsdorf@outlook.com
description: >-
  The official announcement and communication feed for the Arctic Llamas Troop.
  Subscribe for real-time updates and RSVP links.

# Your CRITICAL settings for deployment and URL
baseurl: "" 
url: "https://arcticllamasannouncements.github.io" 

twitter_username: jekyllrb
github_username: ArcticLlamasAnnouncements

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Feed settings to ensure the RSS file is generated
feed:
  path: feed.xml

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/